### ISSUE TITLE
Add example for using a custom annotation

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/navigation-ios-examples#13]
An example highlighting how to use [`navigationMapView(_:imageFor:)`](https://www.mapbox.com/mapbox-navigation-ios/navigation/0.13.1/Protocols/NavigationViewControllerDelegate.html#/c:@M@MapboxNavigation@objc(pl)MBNavigationViewControllerDelegate(im)navigationMapView:imageFor:) or [`navigationMapView(_:viewFor:)`](https://www.mapbox.com/mapbox-navigation-ios/navigation/0.13.1/Protocols/NavigationViewControllerDelegate.html#/c:@M@MapboxNavigation@objc(pl)MBNavigationViewControllerDelegate(im)navigationMapView:viewFor:) would be useful to help illustrate how to add a custom annotation to a turn-by-turn navigation view.

cc @bsudekum

**Comment by bsudekum** [comment]
Done in https://github.com/mapbox/navigation-ios-examples/pull/16
