### ISSUE TITLE
Add offline navigation example

### ISSUE THREAD

**Issue by 1ec5** [mapbox/navigation-ios-examples#41]
Currently there’s only an offline navigation example in the navigation SDK’s repository, but it only shows how to download routing tiles, not map tiles. [This branch](https://github.com/mapbox/mapbox-navigation-ios/compare/1ec5-example-offline-objc-map/) (mapbox/mapbox-navigation-ios@a1ed4fc80220bf0344eae495faf147bb8c307660 … mapbox/mapbox-navigation-ios@26080e54b51dadc5d81262297fc329863f480cec) shows how to download both map and routing tiles offline in Objective-C. We should add a Swift example to this repository.

/cc @mapbox/navigation-ios @geografa @ce-goddard

**Comment by gfoldv** [comment]
I would be interested to put together this example, unless only internal contributors are allowed. Is there any UX/UI concept explaining how this should work?

**Comment by 1ec5** [comment]
You’re more than welcome to contribute an example to this repository, @gfoldv. This repository is primarily meant to power the [SDK examples site](http://docs.mapbox.com/ios/navigation/examples/), so we haven’t given any though to the UX of the example application. But it’s best to keep individual examples as simple and unadorned as possible. We want a developer reading the example’s source code to understand clearly how to find and use the customization hooks, so that they can bring in their own design after reading the code.

**Comment by 1ec5** [comment]
The offline navigation functionality was deprecated in mapbox/mapbox-navigation-ios#2509. The plan was to replace it with a more streamlined offline navigation feature that integrated with the map SDK in mapbox/mapbox-navigation-ios#2653 mapbox/mapbox-navigation-ios#2704, but that feature was canceled in mapbox/mapbox-navigation-ios#2712 in favor of a new offline caching feature that will be coming to a future version of the map and navigation SDKs.

The original offline navigation functionality will be going away in the next major version of the navigation SDK. In the meantime, it remains functional but deprecated, so not something that we’d want to encourage developers to dig into unless they know what they’re doing.

We’ll track an example for the more robust offline navigation feature in a separate issue once the feature is available. In the short term, if you need to get up and running with offline navigation and don’t mind its inefficiencies or planned future removal, #45 could be a good starting point. Quite a bit of the MapboxDirections and MapboxCoreNavigation public API have changed since that PR was opened, but the general structure remains the same, especially when it comes to the deprecated offline map and navigation functionality.
