### ISSUE TITLE
Add example of location snapping in standalone map view

### ISSUE THREAD

**Issue by 1ec5** [mapbox/navigation-ios-examples#72]
As of mapbox/mapbox-navigation-ios#2410, the developer can hook up a PassiveLocationManager to a map view outside of active turn-by-turn navigation, such as for browsing or previewing a route, to snap location updates to the road network. This feature is also called “free-driving localization”, but we should probably title the example something more task-oriented, like “Snapping locations in standalone map view”, so that the developer doesn’t overlook this example thinking it has to do with avoiding tolls or translating guidance instructions.

/cc @mapbox/navigation-ios

**Comment by azarovalex** [comment]
The example has been added.
